replicaCount: 1

image:
  repository: nginx
  tag: 1.27-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: agenticka-platforma.apps.cgistodulky.cz
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: agenticka-platforma-tls

resources: {}
